### ISSUE TITLE
Poi版本10.6.0無法使用此插件

### ISSUE THREAD

**Issue by darkwang2003** [Sunev/poi-plugin-kanmusu_list#1]
在Poi版本10.6.0下使用此插件無反應。
可以的話，作者您可以更新新版本嗎?
畢竟Poi沒有內建轉碼插件，十分不便。
而您的插件十分好用，整理艦娘資料非常快速。

**Comment by Sunev** [comment]
在我的poi 10.6.0没有重现此问题，如果在poi开发者工具中有相关的报错信息，请一同提供，以便排查问题

**Comment by darkwang2003** [comment]
RangeError: Maximum call stack size exceeded
    at getSeries (C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-kanmusu_list-1.0.0\index.es:62:19)
    at getSeries (C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-kanmusu_list-1.0.0\index.es:70:14)
    at getSeries (C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-kanmusu_list-1.0.0\index.es:70:14)
    中間大概有幾百還是幾千筆相同的資料
    at getSeries (C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-kanmusu_list-1.0.0\index.es:70:14)
    at generateKanmusuList (C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-kanmusu_list-1.0.0\index.es:36:18)
    at reducer (C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-kanmusu_list-1.0.0\index.es:110:19)
    at combination (C:\Program Files\poi\resources\app.asar\views\redux\combine-reducers.es:76:31)
    at C:\Program Files\poi\resources\app.asar\views\redux\index.es:53:18
    at combination (C:\Program Files\poi\resources\app.asar\views\redux\combine-reducers.es:76:31)
    at combination (C:\Program Files\poi\resources\app.asar\views\redux\combine-reducers.es:76:31)
    at dispatch (C:\Program Files\poi\resources\app.asar\node_modules\redux\lib\redux.js:219:22)
    at C:\Program Files\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:14:16
    at C:\Program Files\poi\resources\app.asar\views\middlewares\promise-action.es:55:12
    at C:\Program Files\poi\resources\app.asar\node_modules\redux\lib\redux.js:483:12
    at Object.ba (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:84)
    at ja (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:238)
    at ka (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:292)
    at oa (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:15:72)
    at lc (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:52:170)
    at jc (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:51:255)
    at mc (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:52:334)
    at sc (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:56:10)
    at Ia (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:287:189)
    at Ma (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:19:57)
    at Rc (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:70:279)
    at id (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:69:102)
    at exports.unstable_runWithPriority (C:\Program Files\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:19:467)
    at cg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at Ga (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:287:48)
    at gd (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:68:371)

**Comment by darkwang2003** [comment]
以上供您參考

**Comment by Sunev** [comment]
请尝试更新此数据，检查是否改善
![$~NDO~_BFGD{WZ4`)VJD8A1](https://user-images.githubusercontent.com/12387091/84731518-b0f09480-afcb-11ea-8c85-19d62047d97c.png)

**Comment by darkwang2003** [comment]
跟您的版本相同，也按更新了，同樣無效。
我下午試試把poi重新安裝一次試試看。

**Comment by darkwang2003** [comment]
有新的錯誤了
先出現以下錯誤，然後接上面那一堆錯誤。
C:\Program Files\poi\resources\app.asar\node_modules\@babel\generator\lib\index.js:66 [BABEL] Note: The code generator has deoptimised the styling of C:\Program Files\poi\resources\app.asar\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
normalizeOptions @ C:\Program Files\poi\resources\app.asar\node_modules\@babel\generator\lib\index.js:66

**Comment by Sunev** [comment]
是Fletcher改二之后出现的死循环问题，Fletcher改的ID比改二大，蛮离奇的
我一直没改二所以没有触发。。。

**Comment by darkwang2003** [comment]
哈哈，原來如此，有找到根源就好了，感謝作者的辛勞。
